<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-6KM9G37" failures="1" tests="6" name="testCase" time="0.394" errors="0" timestamp="2021-06-30T01:12:50 IST">
  <testcase classname="test.Rerun.RetryTestCases" name="test1" time="0.063">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="test.Rerun.RetryTestCases" name="test1" time="0.009">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="test.Rerun.RetryTestCases" name="test1" time="0.007">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="test.Rerun.RetryTestCases" name="test1" time="0.005">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="test.Rerun.RetryTestCases" name="test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at test.Rerun.RetryTestCases.test1(RetryTestCases.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="test.Rerun.RetryTestCases" name="test2" time="0.002"/>
</testsuite> <!-- testCase -->
